# Generated by Django 3.1.2 on 2020-10-09 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='broadcast_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.broadcasttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_comments', to='core.broadcast'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.broadcast'),
        ),
    ]
