# Generated by Django 3.1.2 on 2020-10-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201009_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='link',
            field=models.URLField(default='google.com'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='broadcasttype',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='broadcasttype',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
